---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankRequest
  labels:
    app: BankRequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankRequest
  template:
    metadata:
      labels:
        app: BankRequest
    spec:
      containers:
        - name: BankRequest
          image: username/BankRequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAuthentication
  labels:
    app: BankAuthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAuthentication
  template:
    metadata:
      labels:
        app: BankAuthentication
    spec:
      containers:
        - name: BankAuthentication
          image: username/BankAuthentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAccount
  labels:
    app: BankAccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAccount
  template:
    metadata:
      labels:
        app: BankAccount
    spec:
      containers:
        - name: BankAccount
          image: username/BankAccount:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankMessage
  labels:
    app: BankMessage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankMessage
  template:
    metadata:
      labels:
        app: BankMessage
    spec:
      containers:
        - name: BankMessage
          image: username/BankMessage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankLoan
  labels:
    app: BankLoan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankLoan
  template:
    metadata:
      labels:
        app: BankLoan
    spec:
      containers:
        - name: BankLoan
          image: username/BankLoan:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAccountHistory
  labels:
    app: BankAccountHistory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAccountHistory
  template:
    metadata:
      labels:
        app: BankAccountHistory
    spec:
      containers:
        - name: BankAccountHistory
          image: username/BankAccountHistory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: BankRequest
  labels:
    app: BankRequest
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankRequest


---


apiVersion: v1
kind: Service
metadata:
  name: BankAuthentication
  labels:
    app: BankAuthentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankAuthentication


---


apiVersion: v1
kind: Service
metadata:
  name: BankAccount
  labels:
    app: BankAccount
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankAccount


---


apiVersion: v1
kind: Service
metadata:
  name: BankMessage
  labels:
    app: BankMessage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankMessage


---


apiVersion: v1
kind: Service
metadata:
  name: BankLoan
  labels:
    app: BankLoan
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankLoan


---


apiVersion: v1
kind: Service
metadata:
  name: BankAccountHistory
  labels:
    app: BankAccountHistory
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankAccountHistory

